#!/bin/tcsh

cp /usr/home/kymafur/.config/awesome/termthemes/Xtrunks /usr/home/kymafur/.Xresources
xrdb -load /usr/home/kymafur/.Xresources
echo 'rofi.theme: /usr/home/kymafur/.config/rofi/trunkstheme' > .config/rofi/config

